/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define I2C_DRIVER I2CD1
#define I2C1_SCL_PIN GP3
#define I2C1_SDA_PIN GP2

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define VIAL_TAP_DANCE_ENTRIES 15
#define VIAL_COMBO_ENTRIES 40
#define VIAL_KEYBOARD_UID {0xDA, 0x2A, 0xFA, 0x9D, 0x66, 0xE4, 0x31, 0x52}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 4 }

#define NO_ALT_REPEAT_KEY

#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_SPLIT
#define RGBLIGHT_DEFAULT_HUE 110
#define RGBLIGHT_LIMIT_VAL 10
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS
#define RGBLIGHT_HUE_STEP 20
#define WS2812_DI_PIN GP16
