VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = yes
QMK_SETTINGS = yes
REPEAT_KEY_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

VIAL_INSECURE = no
