VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
QMK_SETTINGS = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

I2C_DRIVER_REQUIRED = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

KEY_OVERRIDE_ENABLE = no
VIAL_INSECURE = no

OPT_DEFS += -DHAL_USE_I2C=TRUE
